"""Extract normalized OSNet features from the saved Re-ID crop manifest."""

import argparse
from collections import Counter
from datetime import datetime, timezone
import hashlib
from importlib.metadata import version
import json
from pathlib import Path
import platform

ROOT = Path(__file__).resolve().parents[1]
MEAN = (0.485, 0.456, 0.406)
STD = (0.229, 0.224, 0.225)


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_crops(manifest_path):
    """Keep manifest order; never infer observation IDs from filenames."""
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    configuration = manifest["configuration"]
    if configuration["color"] != "RGB" or configuration["dtype"] != "uint8":
        raise ValueError("Expected an RGB uint8 crop manifest")
    records, paths, keys, seen_paths = [], [], set(), set()
    base = manifest_path.parent.resolve()
    for index, item in enumerate(manifest["crops"]):
        if item["status"] == "skipped_fully_outside":
            continue
        if item["status"] != "saved":
            raise ValueError(f"Unknown crop status at manifest index {index}")
        key = tuple(item[name] for name in ("camera", "local_id", "frame_index"))
        if any(type(value) is not int or value < 0 for value in key) or key in keys:
            raise ValueError(f"Invalid or duplicate observation key: {key}")
        relative = Path(item["crop_path"])
        path = (base / relative).resolve()
        if relative.is_absolute() or not path.is_relative_to(base):
            raise ValueError(f"Crop path must stay inside the crop directory: {relative}")
        if path in seen_paths:
            raise ValueError(f"Crop file used more than once: {relative}")
        if any(type(item[name]) is not int or item[name] <= 0 for name in ("width", "height")):
            raise ValueError(f"Invalid crop dimensions: {relative}")
        keys.add(key)
        seen_paths.add(path)
        records.append({**item, "embedding_row": len(records),
                        "source_manifest_index": index})
        paths.append(path)
    if not records:
        raise ValueError("No saved crops in the input manifest")
    counts = Counter(item["camera"] for item in records)
    declared = {item["camera"]: item["saved_crops"] for item in manifest["cameras"]}
    if len(declared) != len(manifest["cameras"]) or any(
        counts[camera] != count for camera, count in declared.items()
    ) or set(counts) - set(declared):
        raise ValueError("Camera totals do not match saved crop records")
    return manifest, records, paths


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True,
                        help="manifest.json generated by preview_reid_crops.py")
    parser.add_argument("--model-config", type=Path,
                        default=ROOT / "configs/models/osnet_x1_0_msmt17.json")
    args = parser.parse_args()
    manifest_path = args.manifest.resolve()
    config_path = args.model_config.resolve()
    source_manifest_hash = sha256(manifest_path)
    crop_manifest, records, paths = read_crops(manifest_path)
    config = json.loads(config_path.read_text(encoding="utf-8"))
    if (config["architecture"] != "osnet_x1_0" or config["feature_dim"] != 512
            or config["input_size_hw"] != [256, 128]):
        raise ValueError("This preview expects OSNet x1.0, 512 features, input H=256 W=128")
    for name, spec in config["assets"].items():
        if sha256(ROOT / spec["path"]) != spec["sha256"]:
            raise RuntimeError(f"Model asset checksum mismatch: {name}")
    print("Model asset checksums: VERIFIED", flush=True)

    import numpy as np
    from PIL import Image
    import torch
    from torch.nn import functional as F
    from torchvision import transforms
    from mtmc.reid._vendor.osnet import osnet_x1_0

    if not torch.cuda.is_available():
        raise RuntimeError("This FP32 baseline requires CUDA")
    torch.backends.cuda.matmul.allow_tf32 = False
    torch.backends.cudnn.allow_tf32 = False
    torch.backends.cudnn.benchmark = False
    torch.set_default_dtype(torch.float32)
    preprocess = transforms.Compose([
        transforms.Resize((256, 128), interpolation=transforms.InterpolationMode.BILINEAR,
                          antialias=True),
        transforms.ToTensor(),
        transforms.Normalize(mean=MEAN, std=STD),
    ])
    tensors = []
    for item, path in zip(records, paths):
        item["crop_sha256"] = sha256(path)
        with Image.open(path) as image:
            if image.format != "PNG" or image.mode != "RGB":
                raise ValueError(f"Expected an original RGB PNG crop: {path}")
            if image.size != (item["width"], item["height"]):
                raise ValueError(f"Image dimensions do not match manifest: {path}")
            tensors.append(preprocess(image))
    inputs = torch.stack(tensors)
    if (tuple(inputs.shape) != (len(records), 3, 256, 128)
            or inputs.dtype != torch.float32 or not torch.isfinite(inputs).all().item()):
        raise RuntimeError("Invalid preprocessed input tensor")
    print(f"Crops per camera: {dict(sorted(Counter(r['camera'] for r in records).items()))}")
    print(f"Input shape: {tuple(inputs.shape)}", flush=True)

    state = torch.load(ROOT / config["assets"]["weights"]["path"],
                       map_location="cpu", weights_only=True)
    model = osnet_x1_0(num_classes=config["checkpoint_num_classes"], pretrained=False)
    model.load_state_dict(state, strict=True)
    model = model.eval().to(device="cuda:0", dtype=torch.float32)
    inputs = inputs.to(device="cuda:0", dtype=torch.float32)
    with torch.inference_mode():
        features = model(inputs)
        if (tuple(features.shape) != (len(records), 512)
                or features.dtype != torch.float32 or not torch.isfinite(features).all().item()):
            raise RuntimeError("Invalid OSNet output tensor")
        raw_norms = torch.linalg.vector_norm(features, ord=2, dim=1)
        if not torch.isfinite(raw_norms).all().item() or (raw_norms <= 1e-12).any().item():
            raise RuntimeError("Cannot normalize a zero or invalid embedding")
        embeddings = F.normalize(features, p=2, dim=1).cpu().numpy()
        raw_norms = raw_norms.cpu().numpy()
    norms = np.linalg.norm(embeddings, axis=1)
    if not np.isfinite(embeddings).all() or not np.allclose(norms, 1.0, rtol=0, atol=1e-5):
        raise RuntimeError("L2 normalization check failed")
    for item, raw_norm in zip(records, raw_norms):
        item["raw_feature_l2_norm"] = float(raw_norm)

    now = datetime.now(timezone.utc)
    output = ROOT / "artifacts/reid_embeddings" / now.strftime("%Y%m%dT%H%M%S%fZ")
    output.mkdir(parents=True, exist_ok=False)
    embedding_path = output / "embeddings.npy"
    np.save(embedding_path, embeddings, allow_pickle=False)
    report = {
        "schema_version": 1,
        "created_utc": now.isoformat(),
        "source_manifest": {"path": str(manifest_path), "sha256": source_manifest_hash},
        "source_tracks": crop_manifest["tracks"],
        "model_configuration": config,
        "model_config_file": {"path": str(config_path), "sha256": sha256(config_path)},
        "preprocessing": {
            "color": "RGB", "source_dtype": "uint8", "input_size_hw": [256, 128],
            "resize": "PIL bilinear, antialias=True, direct resize, no padding",
            "pixel_scaling": "uint8 / 255", "mean": MEAN, "std": STD,
            "layout": "NCHW", "augmentation": "none",
        },
        "inference": {
            "device": str(next(model.parameters()).device),
            "dtype": str(next(model.parameters()).dtype), "mode": "eval + inference_mode",
            "batch_size": len(records), "matmul_tf32": False, "cudnn_tf32": False,
            "cudnn_benchmark": False, "gpu": torch.cuda.get_device_name(0),
            "cuda_build": torch.version.cuda,
        },
        "versions": {"python": platform.python_version(), **{
            package: version(package) for package in ("torch", "torchvision", "numpy", "pillow")
        }},
        "script_sha256": sha256(Path(__file__)),
        "embeddings": {
            "path": embedding_path.name, "sha256": sha256(embedding_path),
            "shape": list(embeddings.shape), "dtype": str(embeddings.dtype),
            "normalization": "L2 per row", "norm_min": float(norms.min()),
            "norm_max": float(norms.max()),
        },
        "observation_key": ["camera", "local_id", "frame_index"],
        "row_order": "Saved crop records in source manifest order",
        "crop_path_base": str(manifest_path.parent),
        "note": "Local IDs are scoped to the source tracking run and camera. No global IDs assigned.",
        "records": records,
    }
    report_path = output / "manifest.json"
    report_path.write_text(json.dumps(report, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    print("Weights: loaded with strict=True")
    print(f"Model device: {next(model.parameters()).device}")
    print(f"Model dtype: {next(model.parameters()).dtype}")
    print(f"Output shape: {embeddings.shape}")
    print(f"Normalized L2 norms: min={norms.min():.8f}, max={norms.max():.8f}")
    print(f"Embeddings: {embedding_path}")
    print(f"Report: {report_path}")
    print("OSNet crop embeddings: PASSED")


if __name__ == "__main__":
    main()
